# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_predmet_prepad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekzamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u044d\u043a\u0437\u0430\u043c\u0435\u043d\u0430')),
                ('predmet_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Predmet', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u0430')),
                ('prepad_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Prepad', verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('student_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430')),
            ],
            options={
                'verbose_name': '\u042d\u043a\u0437\u0430\u043c\u0435\u043d',
                'verbose_name_plural': '\u042d\u043a\u0437\u0430\u043c\u0435\u043d',
            },
        ),
    ]
