# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160216_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekzamen',
            name='predmet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Predmet', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='ekzamen',
            name='prepad_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Prepad', verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
